name: lua cjson wasm pipeline
on: [push]
jobs:
    pipeline:
        runs-on: ubuntu-latest
        steps:
            - name: Dockerhub log in
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            - run: ./bin/test-lua-runner
