name: pipeline
on: [push]
jobs:
    pipeline:
        runs-on: ubuntu-latest
        steps:
            - name: Dockerhub log in
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            - name: Check out repository code
              uses: actions/checkout@v2
            - name: Run lua-runner tests
              run: ./bin/test-lua-runner
